services:
  form-mcp:
    build: .
    container_name: form-mcp-server
    restart: unless-stopped
    ports:
      - "3002:3002"
    volumes:
      # Persist form data
      - ./data:/data
      # Create a named volume for forms.json to avoid permission issues
      - form-data:/app
    environment:
      - MCP_PORT=3002
      - MCP_HOSTNAME=homoiconicity.tail663e6.ts.net
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3002/health', (res) => process.exit(res.statusCode === 200 ? 0 : 1))"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - mcp-network

networks:
  mcp-network:
    driver: bridge

volumes:
  form-data: