/** @type {import("prettier").Config} */
export default {
  semi: true,
  trailingComma: "es5",
  singleQuote: false,
  printWidth: 80,
  tabWidth: 2,
  useTabs: false,
  endOfLine: "lf",
  arrowParens: "always",
  bracketSpacing: true,
  bracketSameLine: false,
  quoteProps: "as-needed",
  proseWrap: "preserve",
  insertPragma: false,
  requirePragma: false,
  embeddedLanguageFormatting: "auto",
  htmlWhitespaceSensitivity: "css",
  vueIndentScriptAndStyle: false,
  singleAttributePerLine: false,
}; 